In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
config={
    
    'Path': r"D:\Github\NLP_Duplicate_questions\quora-question-pairs\train.csv\train.csv"
    
}

In [4]:
main_df=pd.read_csv(config['Path'])
# main_df=pd.read_csv(r"D:\Github\NLP_Duplicate_questions\BOW_Data.csv")
main_df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [5]:
df=main_df.sample(25000,random_state=69)
del main_df

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 188277 to 237324
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            25000 non-null  int64
 1   qid1          25000 non-null  int64
 2   qid2          25000 non-null  int64
 3   question1     25000 non-null  object
 4   question2     25000 non-null  object
 5   is_duplicate  25000 non-null  int64
dtypes: int64(4), object(2)
memory usage: 1.3+ MB

In [7]:
# funny = df[df['id']==404289]
df.isna().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [8]:
df=df.dropna()
df.isna().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [9]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
188277,188277,286753,286754,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,0
325462,325462,160263,451717,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,0
25041,25041,1775,46708,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,1
53446,53446,94485,94486,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,0
321887,321887,380388,447645,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,0

In [10]:
ndf=df[['question1','question2']]
ndf

,question1,question2
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?
...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?
112032,What is an alkali?,What is alkali?
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?
237324,Can I make $50 million from poker?,How much can I make playing poker?

# Cooking Features

### Len of q1 & q2

In [11]:
ndf['len_q1']=ndf['question1'].str.len()
ndf['len_q2']=ndf['question2'].str.len()
ndf

,question1,question2,len_q1,len_q2
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,36,67
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,147,147
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,79,56
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,74,70
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,45,38
...,...,...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?,78,46
112032,What is an alkali?,What is alkali?,18,15
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?,32,37
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?,64,36
237324,Can I make $50 million from poker?,How much can I make playing poker?,34,34

### Number of words in q1 & q2

In [12]:
ndf['num_words_q1']=ndf['question1'].apply(lambda row: len(row.split(' ')))
ndf['num_words_q2']=ndf['question2'].apply(lambda row: len(row.split(' ')))
ndf

,question1,question2,len_q1,len_q2,num_words_q1,num_words_q2
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,36,67,9,12
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,147,147,27,31
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,79,56,17,12
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,74,70,14,13
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,45,38,8,9
...,...,...,...,...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?,78,46,14,8
112032,What is an alkali?,What is alkali?,18,15,4,3
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?,32,37,7,7
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?,64,36,12,6
237324,Can I make $50 million from poker?,How much can I make playing poker?,34,34,7,7

### Number of common words between both the question

In [13]:
def common_words(row):
    w1 = set(map(lambda word: word.lower().strip(), row['question1'].split(" ")))
    w2 = set(map(lambda word: word.lower().strip(), row['question2'].split(" ")))    
    return len(w1 & w2)

In [14]:
ndf['num_common_words'] = ndf.apply(common_words, axis=1)
ndf

,question1,question2,len_q1,len_q2,num_words_q1,num_words_q2,num_common_words
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,36,67,9,12,3
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,147,147,27,31,8
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,79,56,17,12,11
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,74,70,14,13,4
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,45,38,8,9,1
...,...,...,...,...,...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?,78,46,14,8,3
112032,What is an alkali?,What is alkali?,18,15,4,3,3
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?,32,37,7,7,4
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?,64,36,12,6,1
237324,Can I make $50 million from poker?,How much can I make playing poker?,34,34,7,7,4

### Total number of words

In [15]:
def total_words(row):
    w1 = set(map(lambda word: word.lower().strip(), row['question1'].split(" ")))
    w2 = set(map(lambda word: word.lower().strip(), row['question2'].split(" ")))    
    return (len(w1) + len(w2))

In [16]:
ndf['total_num_words'] = ndf.apply(total_words, axis=1)
ndf

,question1,question2,len_q1,len_q2,num_words_q1,num_words_q2,num_common_words,total_num_words
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,36,67,9,12,3,20
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,147,147,27,31,8,45
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,79,56,17,12,11,28
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,74,70,14,13,4,27
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,45,38,8,9,1,17
...,...,...,...,...,...,...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?,78,46,14,8,3,22
112032,What is an alkali?,What is alkali?,18,15,4,3,3,7
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?,32,37,7,7,4,14
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?,64,36,12,6,1,17
237324,Can I make $50 million from poker?,How much can I make playing poker?,34,34,7,7,4,14

### Ratio of Common words : Total words

In [17]:
ndf['word_share'] = round(ndf['num_common_words']/ndf['total_num_words'],2)
ndf

,question1,question2,len_q1,len_q2,num_words_q1,num_words_q2,num_common_words,total_num_words,word_share
188277,Why do we feel cold when we are ill?,Why do small illnesses like colds make you fee...,36,67,9,12,3,20,0.15
325462,I booked some tickets on BookMyShow using net ...,If I have a debit card and I don't have a cred...,147,147,27,31,8,45,0.18
25041,How on earth would I dress like a workout guy ...,How would I dress like a workout guy from the ...,79,56,17,12,11,28,0.39
53446,What's the best POS system (iPad or not) for a...,What are the most useful gadgets for your iPho...,74,70,14,13,4,27,0.15
321887,Why are clear face masks worn for basketball?,How can I make my face clean and soft?,45,38,8,9,1,17,0.06
...,...,...,...,...,...,...,...,...,...
114566,Where can I get the best digital marketing cou...,Will digital marketing a good course to learn?,78,46,14,8,3,22,0.14
112032,What is an alkali?,What is alkali?,18,15,4,3,3,7,0.43
137390,Is it unsafe to eat moldy fruit?,Is it healthy to eat seedless fruits?,32,37,7,7,4,14,0.29
239967,Is dxtorrent.com the new link to Kickass Torre...,Can Kickass torrent be online again?,64,36,12,6,1,17,0.06
237324,Can I make $50 million from poker?,How much can I make playing poker?,34,34,7,7,4,14,0.29

# Advanced features

In [18]:
from nltk.corpus import stopwords

def fetch_token_features(row):
    
    q1 = row['question1']
    q2 = row['question2']
    
    SAFE_DIV = 0.0001 

    STOP_WORDS = stopwords.words("english")
    
    token_features = [0.0]*8
    
    # Converting the Sentence into Tokens: 
    q1_tokens = q1.split()
    q2_tokens = q2.split()
    
    if len(q1_tokens) == 0 or len(q2_tokens) == 0:
        return token_features

    # Get the non-stopwords in Questions
    q1_words = set([word for word in q1_tokens if word not in STOP_WORDS])
    q2_words = set([word for word in q2_tokens if word not in STOP_WORDS])
    
    #Get the stopwords in Questions
    q1_stops = set([word for word in q1_tokens if word in STOP_WORDS])
    q2_stops = set([word for word in q2_tokens if word in STOP_WORDS])
    
    # Get the common non-stopwords from Question pair
    common_word_count = len(q1_words.intersection(q2_words))
    
    # Get the common stopwords from Question pair
    common_stop_count = len(q1_stops.intersection(q2_stops))
    
    # Get the common Tokens from Question pair
    common_token_count = len(set(q1_tokens).intersection(set(q2_tokens)))
    
    
    token_features[0] = common_word_count / (min(len(q1_words), len(q2_words)) + SAFE_DIV)
    token_features[1] = common_word_count / (max(len(q1_words), len(q2_words)) + SAFE_DIV)
    token_features[2] = common_stop_count / (min(len(q1_stops), len(q2_stops)) + SAFE_DIV)
    token_features[3] = common_stop_count / (max(len(q1_stops), len(q2_stops)) + SAFE_DIV)
    token_features[4] = common_token_count / (min(len(q1_tokens), len(q2_tokens)) + SAFE_DIV)
    token_features[5] = common_token_count / (max(len(q1_tokens), len(q2_tokens)) + SAFE_DIV)
    
    # Last word of both question is same or not
    token_features[6] = int(q1_tokens[-1] == q2_tokens[-1])
    
    # First word of both question is same or not
    token_features[7] = int(q1_tokens[0] == q2_tokens[0])
    
    return token_features

In [22]:
import distance

def fetch_length_features(row):
    
    q1 = row['question1']
    q2 = row['question2']
    
    length_features = [0.0]*3
    
    # Converting the Sentence into Tokens: 
    q1_tokens = q1.split()
    q2_tokens = q2.split()
    
    if len(q1_tokens) == 0 or len(q2_tokens) == 0:
        return length_features
    
    # Absolute length features
    length_features[0] = abs(len(q1_tokens) - len(q2_tokens))
    
    #Average Token Length of both Questions
    length_features[1] = (len(q1_tokens) + len(q2_tokens))/2
    
    strs = list(distance.lcsubstrings(q1, q2))
    length_features[2] = len(strs[0]) / (min(len(q1), len(q2)) + 1)
    
    return length_features

In [24]:
from fuzzywuzzy import fuzz

def fetch_fuzzy_features(row):
    
    q1 = row['question1']
    q2 = row['question2']
    
    fuzzy_features = [0.0]*4
    
    # fuzz_ratio
    fuzzy_features[0] = fuzz.QRatio(q1, q2)

    # fuzz_partial_ratio
    fuzzy_features[1] = fuzz.partial_ratio(q1, q2)

    # token_sort_ratio
    fuzzy_features[2] = fuzz.token_sort_ratio(q1, q2)

    # token_set_ratio
    fuzzy_features[3] = fuzz.token_set_ratio(q1, q2)

    return fuzzy_features

In [19]:
token_features = new_df.apply(fetch_token_features, axis=1)

new_df["cwc_min"]       = list(map(lambda x: x[0], token_features))
new_df["cwc_max"]       = list(map(lambda x: x[1], token_features))
new_df["csc_min"]       = list(map(lambda x: x[2], token_features))
new_df["csc_max"]       = list(map(lambda x: x[3], token_features))
new_df["ctc_min"]       = list(map(lambda x: x[4], token_features))
new_df["ctc_max"]       = list(map(lambda x: x[5], token_features))
new_df["last_word_eq"]  = list(map(lambda x: x[6], token_features))
new_df["first_word_eq"] = list(map(lambda x: x[7], token_features))

ength_features = new_df.apply(fetch_length_features, axis=1)

new_df['abs_len_diff'] = list(map(lambda x: x[0], length_features))
new_df['mean_len'] = list(map(lambda x: x[1], length_features))
new_df['longest_substr_ratio'] = list(map(lambda x: x[2], length_features))

fuzzy_features = new_df.apply(fetch_fuzzy_features, axis=1)

# Creating new feature columns for fuzzy features
new_df['fuzz_ratio'] = list(map(lambda x: x[0], fuzzy_features))
new_df['fuzz_partial_ratio'] = list(map(lambda x: x[1], fuzzy_features))
new_df['token_sort_ratio'] = list(map(lambda x: x[2], fuzzy_features))
new_df['token_set_ratio'] = list(map(lambda x: x[3], fuzzy_features))

NameError: name 'new_df' is not defined